### ISSUE TITLE
Can't run `mix ecto.reset`

### ISSUE THREAD

**Issue by tiotolstoy** [oestrich/ex_venture#146]
I get the following error; I have no modified the README.

```
01:02:36.292 [error] GenServer #PID<0.2905.0> terminating
** (RuntimeError) connect raised KeyError exception: key :password not found. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details
    (elixir) lib/keyword.ex:393: Keyword.fetch!/2
    (postgrex) lib/postgrex/protocol.ex:722: Postgrex.Protocol.auth_md5/4
    (postgrex) lib/postgrex/protocol.ex:579: Postgrex.Protocol.handshake/2
    (db_connection) lib/db_connection/connection.ex:69: DBConnection.Connection.connect/2
    (connection) lib/connection.ex:622: Connection.enter_connect/5
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: nil
** (Mix) The database for Data.Repo couldn't be dropped: killed
```

**Comment by tiotolstoy** [comment]
Disregard. Did not read `/setup.md`
