### ISSUE TITLE
Seeds broken / Query error when booting up app

### ISSUE THREAD

**Issue by ghost** [oestrich/ex_venture#147]
I just installed my app. I ran `mix ecto.reset` successfully. I continued by running `mix run --no-halt` and when I visited `localhost:4000`, I got the following error. No changes have been made to the repo itself. I did get the same error when running `mix run priv/repo/seeds.exs`.

```
        + 1 hidden module
01:21:24.834 [error] GenServer Game.Config terminating
** (Ecto.MultipleResultsError) expected at most one result but got 2 in query:

from c0 in Data.Config,
  where: c0.name == ^"game_name",
  select: c0.value

    (ecto) lib/ecto/repo/queryable.ex:100: Ecto.Repo.Queryable.one/3
    (ex_venture) lib/game/config.ex:353: Game.Config.handle_call/3
    (stdlib) gen_server.erl:661: :gen_server.try_handle_call/4
    (stdlib) gen_server.erl:690: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message (from #PID<0.893.0>): {:reload, "game_name"}
01:21:24.854 [error] #PID<0.893.0> running Web.Endpoint (connection #PID<0.891.0>, stream id 1) terminated
Server: localhost:4000 (http)
Request: GET /
** (exit) exited in: GenServer.call(Game.Config, {:reload, "game_name"}, 5000)
    ** (EXIT) an exception was raised:
        ** (Ecto.MultipleResultsError) expected at most one result but got 2 in query:

from c0 in Data.Config,
  where: c0.name == ^"game_name",
  select: c0.value

            (ecto) lib/ecto/repo/queryable.ex:100: Ecto.Repo.Queryable.one/3
            (ex_venture) lib/game/config.ex:353: Game.Config.handle_call/3
            (stdlib) gen_server.erl:661: :gen_server.try_handle_call/4
            (stdlib) gen_server.erl:690: :gen_server.handle_msg/6
            (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
```

**Comment by oestrich** [comment]
Generally this is due to running the seeds more than once. They're no idempotent right now. If you run mix ecto.reset with the server off does it still give you an error on boot? Usually running reset (which also runs the seeds) fixes the issue by clearing everything out.
