### ISSUE TITLE
Ecto.InvalidChangesetError when applying seed during setup

### ISSUE THREAD

**Issue by nemmons** [oestrich/ex_venture#38]
Thanks for the super-detailed set up instructions! Everything was going fine until I got to `mix run priv/repo/seeds.exs`, at which point i got the error below. Unfortunately, i'm not well-versed enough in Ecto to debug this on my own yet, so i figured i would report the bug in case it's some sort of trivial fix. Otherwise, i'll try and take a look in the next few days to see if i can resolve the issue on my own. Thanks!

```
** (Ecto.InvalidChangesetError) could not perform insert because changeset is invalid.

Applied changes

    %{
      currency: 100,
      events: [
        %{action: %{type: "target"}, type: "room/entered"},
        %{
          action: %{
            delay: 2.0,
            effects: [%{amount: 2, kind: "damage", type: "slashing"}],
            text: "[user] slashes at you.",
            type: "target/effects",
            weight: 10
          },
          type: "combat/tick"
        }
      ],
      experience_points: 230,
      level: 2,
      name: "Bandit",
      stats: %{
        constitution: 10,
        dexterity: 10,
        health_points: 25,
        intelligence: 10,
        max_health_points: 25,
        max_move_points: 10,
        max_skill_points: 10,
        move_points: 10,
        skill_points: 10,
        strength: 13,
        wisdom: 10
      }
    }

Params

    %{
      "currency" => 100,
      "events" => [
        %{action: %{type: "target"}, type: "room/entered"},
        %{
          action: %{
            delay: 2.0,
            effects: [%{amount: 2, kind: "damage", type: "slashing"}],
            text: "[user] slashes at you.",
            type: "target/effects",
            weight: 10
          },
          type: "combat/tick"
        }
      ],
      "experience_points" => 230,
      "level" => 2,
      "name" => "Bandit",
      "stats" => %{
        constitution: 10,
        dexterity: 10,
        health_points: 25,
        intelligence: 10,
        max_health_points: 25,
        max_move_points: 10,
        max_skill_points: 10,
        move_points: 10,
        skill_points: 10,
        strength: 13,
        wisdom: 10
      }
    }

Errors

    %{events: [{"are invalid", []}]}

Changeset

    #Ecto.Changeset<
      action: :insert,
      changes: %{
        currency: 100,
        events: [
          %{action: %{type: "target"}, type: "room/entered"},
          %{
            action: %{
              delay: 2.0,
              effects: [%{amount: 2, kind: "damage", type: "slashing"}],
              text: "[user] slashes at you.",
              type: "target/effects",
              weight: 10
            },
            type: "combat/tick"
          }
        ],
        experience_points: 230,
        level: 2,
        name: "Bandit",
        stats: %{
          constitution: 10,
          dexterity: 10,
          health_points: 25,
          intelligence: 10,
          max_health_points: 25,
          max_move_points: 10,
          max_skill_points: 10,
          move_points: 10,
          skill_points: 10,
          strength: 13,
          wisdom: 10
        }
      },
      errors: [events: {"are invalid", []}],
      data: #Data.NPC<>,
      valid?: false
    >

    (ecto) lib/ecto/repo/schema.ex:128: Ecto.Repo.Schema.insert!/4
    priv/repo/seeds.exs:281: Seeds.run/0
    (elixir) lib/code.ex:677: Code.require_file/2
    (mix) lib/mix/tasks/run.ex:136: Mix.Tasks.Run.run/5
    (mix) lib/mix/tasks/run.ex:76: Mix.Tasks.Run.run/1

```

**Comment by oestrich** [comment]
This is related to something I changed over the weekend, with events requiring an ID now. There was also an issue with the config being weird for player's saves, that's probably been broken for a while. Everything is up to date on master now and you should be able to seed the db.

Thanks for checking the app out and letting me know of this!
