### ISSUE TITLE
Seed file seems to be broken

### ISSUE THREAD

**Issue by uri** [oestrich/ex_venture#6]
When running

```bash
mix run priv/repo/seeds.exs
```

```
** (KeyError) key :item_ids not found in: %Data.Save{channels: ["global", "newbie"], currency: nil, experience_points: 0, items: nil, level: 1, room_id: {{:., [line: 292], [{:entrance, [line: 292], nil}, :id]}, [line: 292], []}, stats: nil, version: nil, wearing: nil, wielding: nil}
    (stdlib) :maps.update(:item_ids, [{{:., [line: 296], [Data.Item, :instantiate]}, [line: 296], [{:sword, [line: 296], nil}]}], %Data.Save{channels: ["global", "newbie"], currency: nil, experience_points: 0, items: nil, level: 1, room_id: {{:., [line: 292], [{:entrance, [line: 292], nil}, :id]}, [line: 292], []}, stats: nil, version: nil, wearing: nil, wielding: nil})
    (ex_venture) lib/data/save.ex:28: anonymous fn/2 in Data.Save.__struct__/1
    (elixir) lib/enum.ex:1826: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ex_venture) expanding struct: Data.Save.__struct__/1
    priv/repo/seeds.exs:291: Seeds.run/0
```

**Comment by oestrich** [comment]
I tend to not run it often enough, thanks for the issue! They are fixed now as of 1cc85401e1ce872f00fcd7b02e165219b6c3a0d3.
